### ISSUE TITLE
Update to work with Adonis 4

### ISSUE THREAD

**Issue by watzon** [enniel/adonis-lucid-polymorphic#1]

**Comment by dwatts1772** [comment]
+1

**Comment by okurichenko** [comment]
+1

**Comment by willvincent** [comment]
I see your +1, and raise you a PR. ;)

https://github.com/enniel/adonis-lucid-polymorphic/pull/3

**Comment by osman-mohamad** [comment]
is this package work for adonis version 4.* ?

**Comment by willvincent** [comment]
It does with my pull request that has yet to be merged

**Comment by osman-mohamad** [comment]
thanks @willvincent .
@enniel any news about this pull request to make this package work with 4.1 ?

**Comment by enniel** [comment]
Support for Adonis Lucid ^4.1.0 implemented in version 1.0.0. Thanks to everybody!
